// admin-vue/src/components/shared/header.vue

<template>
    <header class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                <a class="navbar-brand" href="/">
                    {{ appName }}
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li v-for="(item,index) in menus" :key="index">
                        <router-link   tag="a" :exact="item.path == '/'" :to="item.path">
                        {{item.text}} 
                        </router-link>
                    </li>
                    <!-- <li>
                        <a href="/">主页</a>
                    </li>
                    <li>
                        <a href="/category">分类</a>
                    </li>
                    <li>
                        <a href="/article">文章</a>
                    </li>
                    <li>
                        <a href="/about">关于</a>
                    </li> -->
                </ul>

                <ul v-if="!userInfo.id" class="nav navbar-nav navbar-right">
                    <li>
                        <router-link class="loginLink" to="/login">登录</router-link>
                    </li>
                </ul>

                <ul v-if="userInfo.id" class="nav navbar-nav navbar-right">
                    <li>
                        <router-link  to="/admin"> {{ userInfo.name }} 你好！</router-link >
                    </li>
                    <li>
                        <a  @click="onLogout" >注销</a>
                    </li>
                </ul>

            </div>
        </div>
    </header>
</template>

<script>
export default {
     props: {
        appName: {
            default: "EnuoCMS"
        },
        userInfo:{
            _id:'',
            userName:''
        },
        menus : {
            default : () => []
        }
    },
    computed: {
        path(){
            return location.pathname;
        }
    },
    methods: {
        onLogout(){
            this.$emit('onLogout');
        }
    }
}
</script>

<style lang="less" scoped>

</style>

// admin-react/src/components/shared/header.jsx
import React from 'react';
import { Link } from 'react-router-dom';
//import Cookies from 'universal-cookie';
//const cookie = new Cookies();

export default class Header extends React.Component {
    // constructor(arg) {
    //     super(arg);
    // }

    // componentWillMount = ()=> {

    // }

    // logout = ()=> {
    //     cookie.remove('ticket');
    // }

    render() {

        let userInfo =  <ul className="nav navbar-nav navbar-right">
                            <li>
                                <Link className="loginLink" to="/login">登录</Link>
                            </li>
                        </ul>;

        if(this.props.userName){
            
            userInfo =  <ul className="nav navbar-nav navbar-right">
                            <li>
                                <Link to="/admin"> {this.props.userName} 你好！</Link>
                            </li>
                            <li>
                                <a onClick={this.props.onLogout} >注销</a>
                            </li>
                        </ul>;
        }

        return (
            <div className="navbar navbar-inverse navbar-fixed-top">
                    <div className="container">
                        <div className="navbar-header">
                            <button type="button" className="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                    <span className="icon-bar"></span>
                                    <span className="icon-bar"></span>
                                    <span className="icon-bar"></span>
                                </button>
                            <a className="navbar-brand" href="/">
                                {this.props.title}
                            </a>
                        </div>
                        <div className="navbar-collapse collapse">
                            <ul className="nav navbar-nav">
                                <li>
                                    <Link to="/">主页</Link>
                                </li>
                                <li>
                                    <Link to="/category">分类</Link>
                                </li>
                                <li>
                                    <Link to="/article">文章</Link>
                                </li>
                                <li>
                                    <Link to="/about">关于</Link>
                                </li>
                            </ul>

                           {userInfo} 
                            
                        </div>
                    </div>
                </div>
        )
    }
}
