// admin-vue/src/components/category/list.vue
<template>
    <div>
        <h2 class="page-header">
            category
        </h2>

        <table class="table">
            <thead>
                <tr>
                    <th>
                        Title
                    </th>
                    <th>
                        EntTypes
                    </th>
                    <th>
                        EntStatus
                    </th>
                    <th>
                        Creater
                    </th>
                    <th>
                        Updater
                    </th>
                    <th>
                        CreateDate
                    </th>
                    <th>
                        UpdateDate
                    </th>
                    <th></th>
                </tr>   
            </thead>

            <tbody>
                 <tr v-for="(item,index) in list" :key="index">
                    <td>
                    {{ item.title }}
                    </td>
                    <td>
                    {{ item.ent_types }}
                    </td>
                    <td>
                    {{ item.ent_status }}
                    </td>
                    <td>
                    {{ item.creater }}
                    </td>
                    <td>
                    {{ item.updater }}
                    </td>
                    <td>
                     {{ item.create_date | formatDate }}
                    </td>
                    <td>
                    {{ item.update_date | formatDate }}
                    </td>
                    <td>
                        <router-link :to="{ name: 'category_edit', params: { id: item.id }}">Edit</router-link>
                        <router-link :to="{ name: 'category_detail', params: { id: item.id }}">Details</router-link>
                    </td>
                </tr>
            </tbody>
    </table>

    </div>
</template>

<script>
import {list} from './service'
import {formatDate} from '../../util';
export default {
    data(){
        return {
            list:[]
        }
    },
    mounted() {
        this.loadData();
    },
    filters:{
        formatDate(time) {
            var date = new Date(time);
            return formatDate(date, "yyyy-MM-dd hh:mm");
        }
    },
    methods: {
        async loadData(){
           var res = await list();
           this.list = res.data;
       }
    }
}
</script>

<style lang="less" scoped>

</style>

// admin-angular2x/src/app/main/category/list.component.ts
import { Component, OnInit } from '@angular/core';
import { CategoryService } from './category.service'

@Component({
    selector: 'app-category-list',
    templateUrl: './list.component.html'
})
export class CategoryListComponent implements OnInit {

    list = [];
    
    constructor(
        private  categoryService: CategoryService
    ) { }

    loadList(){
        var _this = this;
        this.categoryService.getList().then(function(res){
            _this.list = res.data;
        });
    }

    ngOnInit() {
        this.loadList();
    }

}

<div>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Title
                </th>
                <th>
                    EntTypes
                </th>
                <th>
                    EntStatus
                </th>
                <th>
                    Creater
                </th>
                <th>
                    Updater
                </th>
                <th>
                    CreateDate
                </th>
                <th>
                    UpdateDate
                </th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            <tr *ngFor="let item of list">
                <td>
                    {{ item.title }}
                </td>
                <td>
                    {{ item.ent_types }}
                </td>
                <td>
                    {{ item.ent_status }}
                </td>
                <td>
                    {{ item.creater }}
                </td>
                <td>
                    {{ item.updater }}
                </td>
                <td>
                    {{ item.create_date | date: 'yyyy-MM-dd'}}
                </td>
                <td>
                    {{ item.update_date | date: 'yyyy-MM-dd'}}
                </td>
                <td>
                    <a routerLink="{{ '/category/edit/' + item.id }}">Edit</a>
                    <a routerLink="{{ '/category/detail/' + item.id }}">Details</a>
                </td>
            </tr>
        </tbody>
    </table>

</div>
